#!/bin/bash

SET_BG_DEFAULT="/home/daniel/.config/.wallpaper/arch-linux-1.png" #default/fallback bg

restart_waybar() {
    #restart the waybar
    pkill waybar
    waybar & 
}

set_current_background() {
    get_theme

    SET_BG="/home/daniel/.config/themes/$THEME/wallpaper"

    if [[ -z "$SET_BG" ]]; then
        swww img $SET_BG_DEFAULT
    else
        swww img $SET_BG
    fi
}

get_theme() {
    THEME=$(readlink -f ~/.config/waybar/style.css | cut -d '/' -f6)
}

switch_keyboard() {
    hyprctl switchxkblayout $SET_KB next
}

if [[ "$1" == "setbg" ]]; then
    set_current_background
    restart_waybar
fi
